//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Company.FeatureModelLab02
{
	internal static partial class Constants
	{
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string DesignerFileExtension = "FeatureModelLab02";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductName = @"FeatureModelLab02";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string CompanyName = @"Company";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductVersion = "1.0.0.0";

		// Menu definitions
		public static readonly global::System.ComponentModel.Design.CommandID FeatureModelLab02DiagramMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(FeatureModelLab02CommandSetId), 0x10000);
		public static readonly global::System.ComponentModel.Design.CommandID FeatureModelLab02ExplorerMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(FeatureModelLab02CommandSetId), 0x10001);

		// Command definitions
		public static readonly global::System.ComponentModel.Design.CommandID ViewFeatureModelLab02ExplorerCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(FeatureModelLab02CommandSetId), 0x0001);
	
		// Package identifier
		public const string FeatureModelLab02PackageId = "84cd64c5-67ee-4ed1-9a75-83ba806b4399";
		
		// Editor factory identifier
		public const string FeatureModelLab02EditorFactoryId = "00a7dd8c-e45f-4f2e-87ed-c0852b5b268c";
		
		public const string DefaultDiagramExtension = ".diagram";
		
		// Model explorer tool window identifier
		public const string FeatureModelLab02ModelExplorerToolWindowId = "b9ef839f-14e9-443e-87fc-f4720ce5658e";
	}
}
//
// Constants not generated from values in DesignerDefinition.dsl are defined below
//
namespace Company.FeatureModelLab02
{
	internal static partial class Constants
	{
		// Menu identifier
		public const string FeatureModelLab02CommandSetId = "42437613-8d86-4d39-b696-605a8b01bfeb";
	}
}