//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Company.FeatureSpl
{
	internal static partial class Constants
	{
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string DesignerFileExtension = "feature";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductName = @"Ministore";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string CompanyName = @"Variamos";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductVersion = "1.0.0.0";

		// Menu definitions
		public static readonly global::System.ComponentModel.Design.CommandID FeatureSplDiagramMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(FeatureSplCommandSetId), 0x10000);
		public static readonly global::System.ComponentModel.Design.CommandID FeatureSplExplorerMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(FeatureSplCommandSetId), 0x10001);

		// Command definitions
		public static readonly global::System.ComponentModel.Design.CommandID ViewFeatureSplExplorerCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(FeatureSplCommandSetId), 0x0001);
	
		// Package identifier
		public const string FeatureSplPackageId = "6fb3ec30-432b-428f-97bd-990c443a15f0";
		
		// Editor factory identifier
		public const string FeatureSplEditorFactoryId = "81d59881-6d4c-4d3c-b590-f3eedeef0fdf";
		
		public const string DefaultDiagramExtension = ".diagram";
		
		// Model explorer tool window identifier
		public const string FeatureSplModelExplorerToolWindowId = "0c3f615f-1258-4531-9795-629737cc695f";
	}
}
//
// Constants not generated from values in DesignerDefinition.dsl are defined below
//
namespace Company.FeatureSpl
{
	internal static partial class Constants
	{
		// Menu identifier
		public const string FeatureSplCommandSetId = "820e0e9a-6aad-4bc3-b531-c24e1d210c47";
	}
}