//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Company.SplLanguage
{
	internal static partial class Constants
	{
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string DesignerFileExtension = "SplLanguage";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductName = @"Features";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string CompanyName = @"Variamos";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductVersion = "1.0.0.0";

		// Menu definitions
		public static readonly global::System.ComponentModel.Design.CommandID SplLanguageDiagramMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(SplLanguageCommandSetId), 0x10000);
		public static readonly global::System.ComponentModel.Design.CommandID SplLanguageExplorerMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(SplLanguageCommandSetId), 0x10001);

		// Command definitions
		public static readonly global::System.ComponentModel.Design.CommandID ViewSplLanguageExplorerCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(SplLanguageCommandSetId), 0x0001);
	
		// Package identifier
		public const string SplLanguagePackageId = "73551e97-f942-45a6-89f0-12e006505e80";
		
		// Editor factory identifier
		public const string SplLanguageEditorFactoryId = "aab0177a-6704-4fce-9dee-dcc789321e57";
		
		public const string DefaultDiagramExtension = ".diagram";
		
		// Model explorer tool window identifier
		public const string SplLanguageModelExplorerToolWindowId = "fc1481ca-6c14-4994-97de-6423c213cb1c";
	}
}
//
// Constants not generated from values in DesignerDefinition.dsl are defined below
//
namespace Company.SplLanguage
{
	internal static partial class Constants
	{
		// Menu identifier
		public const string SplLanguageCommandSetId = "d95a2ea9-53f4-49c2-b105-cb3d253d43d1";
	}
}