//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Company.LanguageLab03
{
	internal static partial class Constants
	{
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string DesignerFileExtension = "LanguageLab03";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductName = @"LanguageLab03";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string CompanyName = @"Company";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductVersion = "1.0.0.0";

		// Menu definitions
		public static readonly global::System.ComponentModel.Design.CommandID LanguageLab03DiagramMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(LanguageLab03CommandSetId), 0x10000);
		public static readonly global::System.ComponentModel.Design.CommandID LanguageLab03ExplorerMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(LanguageLab03CommandSetId), 0x10001);

		// Command definitions
		public static readonly global::System.ComponentModel.Design.CommandID ViewLanguageLab03ExplorerCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(LanguageLab03CommandSetId), 0x0001);
	
		// Package identifier
		public const string LanguageLab03PackageId = "0e382322-6e06-4539-b5e4-874a29c54f0c";
		
		// Editor factory identifier
		public const string LanguageLab03EditorFactoryId = "9daba1b2-c372-4d4c-a7e3-b5a45a01a486";
		
		public const string DefaultDiagramExtension = ".diagram";
		
		// Model explorer tool window identifier
		public const string LanguageLab03ModelExplorerToolWindowId = "926b9946-0926-4971-8109-947480abdec5";
	}
}
//
// Constants not generated from values in DesignerDefinition.dsl are defined below
//
namespace Company.LanguageLab03
{
	internal static partial class Constants
	{
		// Menu identifier
		public const string LanguageLab03CommandSetId = "9f7e35f2-d423-4a46-a06f-68cc38f539d7";
	}
}